spring:
    application:
        name: Jagent
    data:
        redis:
            host: localhost
            port: 6379

langchain4j:
    open-ai:
        chat-model:
            api-key: 'sk-18c033b115434e8c838b32c2b17be8be'
            base-url: 'https://api.deepseek.com'
            model-name: 'deepseek-chat'
            log-requests: true   #开启请求日志
            log-responses: true  #开启返回日志
        streaming-chat-model:
            api-key: 'sk-18c033b115434e8c838b32c2b17be8be'
            base-url: 'https://api.deepseek.com'
            model-name: 'deepseek-chat'
            log-requests: true   #开启请求日志
            log-responses: true  #开启返回日志
        embedding-model:
            api-key: 'sk-e3a48206756848f7b57ca32598e9fb3b'
            base-url: 'https://dashscope.aliyuncs.com/compatible-mode/v1'
            model-name: 'text-embedding-v4'
            log-requests: true
            log-responses: true

    community:
        redis:
            host: localhost
            port: 6379
            dimension: 1536
            index-name: jagent-rag-index

logging:
    level:
      dev.langchain4j: debug